# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cluster_bis',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/cluster_bis',
                'lib_path': 'cluster_bis'},
  'syms': {'cluster_bis.core': {'cluster_bis.core.foo': ('core.html#foo', 'cluster_bis/core.py')}}}
